### ISSUE TITLE
Urgent Help Needed 

### ISSUE THREAD

**Issue by kalilinux-png** [osparamatrix/ks-orderapi-python#43]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\pythonFile\TradingApi\kotak_api_.py", line 244, in fetch
    data = shubh.quote(code, 'DEPTH')
  File "C:\pythonFile\lib\site-packages\ks_api_client\ks_api.py", line 220, in quote
    quote  =  ks_api_client.QuoteApi(self.api_client).get_market_details_quote(self.consumer_key, \
  File "C:\pythonFile\lib\site-packages\ks_api_client\api\quote_api.py", line 362, in get_market_details_quote
    return self.get_market_details_quote_with_http_info(consumerKey, sessionToken, instrumentTokens, **kwargs)  # noqa: E501
  File "C:\pythonFile\lib\site-packages\ks_api_client\api\quote_api.py", line 466, in get_market_details_quote_with_http_info
    return self.api_client.call_api(
  File "C:\pythonFile\lib\site-packages\ks_api_client\api_client.py", line 354, in call_api
    return self.__call_api(resource_path, method,
  File "C:\pythonFile\lib\site-packages\ks_api_client\api_client.py", line 173, in __call_api
    raise e
  File "C:\pythonFile\lib\site-packages\ks_api_client\api_client.py", line 166, in __call_api
    response_data = self.request(
  File "C:\pythonFile\lib\site-packages\ks_api_client\api_client.py", line 380, in request
    return self.rest_client.GET(url,
  File "C:\pythonFile\lib\site-packages\ks_api_client\rest.py", line 220, in GET
    return self.request("GET", url,
  File "C:\pythonFile\lib\site-packages\ks_api_client\rest.py", line 214, in request
    raise ApiException(status = r.status, reason = r.reason, body = r.data)
ks_api_client.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response body: {"fault":{"code":101504,"type":"Status report","message":"Runtime Error","description":"Send timeout"}}

**Comment by kumarsukhani** [comment]
@kalilinux-png : Why did you closed it?

**Comment by kalilinux-png** [comment]
@kumarsukhani  answered in another  issues do you want me to open all the issue's again
